### ISSUE TITLE
Pressing upload file with no file selected plays loading animation on loop infinitely 

### ISSUE THREAD

**Issue by t-wing11** [McMaster-Baja-Racing/Better-Data-Viewer#22]
When pressing upload files when no files are uploaded the loading animation will play infinitely.

Need to input a check/restriction for pressing upload files based on whether there is a file present in the queue.

**Comment by gr812b** [comment]
a54efcd0a46c702bc7d4e9af375eee6337977d8c
This is fixed, although should be changed into fade away popup
