### ISSUE TITLE
Redesign Upload Modal Functionality 

### ISSUE THREAD

**Issue by t-wing11** [McMaster-Baja-Racing/Better-Data-Viewer#27]
Need to redesign upload modal functionality

Some things to consider:
After uploading, should wipe the existing file from the display
Should display a message saying upload is complete
Should close the modal (if we want to go down that road)

**Comment by gr812b** [comment]
Message saying upload is complete should fade away with no user interaction required, and also should generalize this to be able to be applied in other places such as clicking submit with no file and other short messages
