### ISSUE TITLE
General redesign of button/font/style formatting across the website

### ISSUE THREAD

**Issue by t-wing11** [McMaster-Baja-Racing/Better-Data-Viewer#28]
Need to pick a general display style and stick to it, all dropdowns, buttons, fonts should all stay consistent

Will need to determine which style is the preferred one, run your choice by other people (superficially Kai)

**Comment by gr812b** [comment]
To add specifics:

### Upload modal

#### Page One

- Live data checkbox
- Port / Baud box (too long?)
- Graph type dropdown

#### Page Three

- X and Y axis select boxes
- Add series button
- Dropdown for more options for analyzers

### Upload Modal

- Delete all button (it deletes all data stored on the backend) moved and restyled, can maybe be put in an "options" menu later on
- See https://github.com/McMaster-Baja-Racing/Better-Data-Viewer/issues/27

### Other

- All fonts
- Maybe top bar?
- Overall should make use of more icons, see Font-Awesome for free access to many, helps with clarity
