### ISSUE TITLE
Abort Duplicate Series

### ISSUE THREAD

**Issue by camdnnn** [McMaster-Baja-Racing/Better-Data-Viewer#60]
Currently it is possible to add duplicate series to a graph. This should be updated so that it is no longer possible.

Requirements:
- Duplicate series are not added to graph when attempted (intentionally or not)
- When done with the "Add Series" button, display a message to the user that the series has already been added
- When done through completion of page, do not display any message to the user regarding the duplicate series

**Comment by gr812b** [comment]
Reasoning is that both the "Add series" button and the "Submit graph" button both add it as a unique series, so its common for users to click Add series before submit graph without any changes in between
