### ISSUE TITLE
Sync Video to Data

### ISSUE THREAD

**Issue by camdnnn** [McMaster-Baja-Racing/Better-Data-Viewer#68]
Add a feature that allows you to upload a video for a series which synchronizes the timestamp of the data and video.

Requirements:
- Upload of video connecting the video to a specific series with a time axis
- Show user data range and video at the same time
- Seek of time range which shows the video frame and value of data at a given time

**Comment by gr812b** [comment]
Maybe look at popping out video, using as an element like graph, video player
